packages:
  - apps/*
  - packages/*
catalog:
  dotenv: ^17.2.2
  zod: ^4.1.13
  typescript: ^5
  "@opentelemetry/api": ^1.9.0
  "@opentelemetry/auto-instrumentations-node": ^0.67.1
  "@opentelemetry/exporter-trace-otlp-http": ^0.207.0
  "@opentelemetry/resources": ^2.1.0
  "@opentelemetry/sdk-node": ^0.207.0
  "@opentelemetry/semantic-conventions": ^1.38.0
  "@trpc/server": ^11.7.2
  better-auth: ^1.4.18
  "@trpc/tanstack-react-query": ^11.7.2
  "@trpc/client": ^11.7.2
  "@tanstack/react-query": ^5.90.12
  "@tanstack/react-form": ^1.28.0
  "@polar-sh/better-auth": ^1.6.4
  "@better-auth/expo": ^1.4.18
  drizzle-orm: ^0.45.1
